on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build tools
    steps:
      - uses: actions/checkout@v2
      - uses: karcherm/action-install-watcom@main
      - run: wcl -2 dumpmem.c
      - run: wcc -0 -fo=pcibase.obj pcibase.c
      - run: wcc -3 -fo=pcilib.obj pcilib.c
      - run: wcl -3 pci.c pcibase.obj pcilib.obj
      - run: wcl -0 hw.c pcibase.obj pcilib.obj
      - uses: actions/upload-artifact@v3
        with:
          name: dostools
          path: "*.exe"
