on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build tools
    steps:
      - uses: actions/checkout@v2
      - uses: karcherm/action-install-watcom@main
      - run: wcl -2 dumpmem.c
      - run: wcl -3 pci.c
      - uses: actions/upload-artifact@v3
        with:
          name: dostools
          path: "*.exe"
